apiVersion: v1
kind: Service
metadata:
  name: predict-service
spec:
  type: NodePort  
  selector:
    app: predict
  ports:
    - port: 6000
      targetPort: 5000
      nodePort: 30004  
